substitutions:
  device_name: "athom-sw02"
  friendly_name: "Athom SW02"
  project_name: "athom.sw02"
  project_version: "1.0"

esphome:
  name: "${device_name}"
  name_add_mac_suffix: true
  platform: ESP8266
  board: esp8285
  project:
    name: "${project_name}"
    version: "${project_version}"

api:

ota:

logger:
  baud_rate: 0

web_server:
  port: 80

wifi:
  ap: {} # This spawns an AP with the device name and mac address with no password.

captive_portal:

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

  # Touch Buttons
  - platform: gpio
    pin:
      inverted: true
      number: GPIO3
    name: "${friendly_name} Button 1"
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at least 0.2s
        then:
          - light.toggle: light1
      - timing:
          - ON for at least 4s
        then:
          - switch.turn_on: restart_switch
  - platform: gpio
    pin:
      inverted: true
      number: GPIO5
    name: "${friendly_name} Button 2"
    disabled_by_default: true
    on_click:
      max_length: 0.5s
      then:
        - light.toggle: light2

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime Sensor"

switch:
  - platform: restart
    id: restart_switch
    name: "${friendly_name} Restart"

output:
  # Relays
  - platform: gpio
    pin: GPIO13
    id: relay1
  - platform: gpio
    pin: GPIO4
    id: relay2

  # Button LEDs (1.0 = Blue / 0.0 = Red)
  - platform: esp8266_pwm
    pin: GPIO14
    inverted: true
    id: led1
  - platform: esp8266_pwm
    pin: GPIO1
    inverted: true
    id: led2

light:
  - platform: status_led
    name: "${friendly_name} Wifi LED"
    disabled_by_default: true
    pin:
      number: GPIO0
      inverted: true

  # Relays
  - platform: binary
    name: "${friendly_name} Light 1"
    id: light1
    output: relay1
    on_turn_on:
      - light.turn_on: light3
    on_turn_off:
      - light.turn_off: light3
  - platform: binary
    name: "${friendly_name} Light 2"
    id: light2
    output: relay2
    on_turn_on:
      - light.turn_on: light4
    on_turn_off:
      - light.turn_off: light4

  # Button LEDs
  - platform: monochromatic
    name: "${friendly_name} LED1"
    disabled_by_default: true
    id: light3
    output: led1
    default_transition_length: 500ms
  - platform: monochromatic
    name: "${friendly_name} LED2"
    disabled_by_default: true
    id: light4
    output: led2
    default_transition_length: 500ms
